version: '3.8'

services:
  confirmme:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - confirmmenet

networks:
  confirmmenet:
    driver: bridge
