
name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Test .NET 8 App
    runs-on: ubuntu-latest

    steps:
      - name: 🛒 Checkout Repository
        uses: actions/checkout@v3

      - name: 🛠 Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: 📦 Restore Dependencies
        run: dotnet restore

      - name: 🔨 Build Project
        run: dotnet build --no-restore

      - name: ✅ Run Tests (jika ada)
        run: dotnet test --no-build --verbosity normal
